- Explorer-Release-Setup-Instructions.md
Added `--restart unless-stopped` to the `docker run` command to automatically start the storagenode docker container in case of system restart (manual or due to power outage).
More info about this option is available here: https://docs.docker.com/config/containers/start-containers-automatically/
> Automatically start the docker container

- Explorer-Release-Setup-Instructions.md
As Docker on Windows is very picky, it seems like this command is the most solid across all installs so far, sometimes the single backslash works, sometimes it don't.
To make sure that it works, double backslash is the way to go
> Make Windows Paths more solid

- code/Style.md
The main goal of this PR is to indicate that every package should have a concise documentation of its purpose.
I added my opinion in where to write the _package comment_ on each package, believing that the solution doesn't make the author to doubt about, but if the opinion isn't shared, I'm fine in modifying/removing such part.
As usual, any other feedback will be appreciated because the end goal is to have collective conventions.
> code/style: add convention for pkg docs

- Explorer-Release-Setup-Instructions.md
Would require some verification if this works as intended. Both storagenode and watchtower run fine with these changes, but haven't confirmed updates work on storagenode container but not on others.
> Limit watchtower updates to storagenode container

- code/Style.md
Add the section _integers_ to the code style document to clarify the exceptional cases that _unsigned integers_ are used.
> code: Add integers code Style doc

- Explorer-Release-Setup-Instructions.md
Add a note in the Explorer release setup instructions document to
mention the requirements that the storage file system must fulfill.
See: https://github.com/storj/storj/issues/1947
> Explorer: Add note storage file system requirements

- Explorer-Release-Setup-Instructions.md
The difference between them: https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior
Because the -v and --volume flags have been a part of Docker for a long time, their behavior cannot be changed. This means that *there is one behavior that is different between -v and --mount*.
If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v creates the endpoint for you. *It is always created as a directory*.
If you use --mount to bind-mount a file or directory that does not yet exist on the Docker host, Docker does not automatically create it for you, but generates an error.
This should save our SNO on Windows and MacOS from losing data during bugs in docker itself, when it doesn't map the data folder from the …
> Explorer-release-setup-instructions: Replace volume binding with mount

- code/payments/Accounting.md
Use the same names for the DB columns mentioned in the document and fix
a typo in one of their references.
> payments/Accounting: Use same column naming

- Explorer-Release-Setup-Instructions.md
I added a section in to inform how to execute other storagenode commands.
I also changed the section level to follow the order, however if the 4th level was the one wanted rather than the 2nd one, do let me know and I will drop that commit.
> The Explorer release: Add section in how to execute other storagenode commands

- Test-network.md
It's does not work with go 1.11 anymore
> The go version update

- Explorer-Release-Setup-Instructions.md
Due to problems authorizing identities with 0.13.5, reverting back to 0.12.6 for now.
> Revert identity links to 0.12.6

- Storage-Node-Setup-Instructions.md
On slower performing systems the default 10s is not enough to stop the container gracefully. Extending the stop timeout prevents damage to info.db due to the container being killed forcefully after 10s. This prevents issue  https://github.com/storj/storj/issues/2300
Thanks @AlexandrTyshchenko for pointing this out and suggesting a solution.
> Prevent KILL by extending stop-timeout in run command

- Storage-Node-Setup-Instructions.md
This update has shown watchtower misreads the docker API version and thinks it's incompatible with this parameter. This results in watchtower stopping your node and pulling a new image, but not starting it again. Reverting to prevent further update issues.
> Revert stop-timeout PR due to watchtower issues

- Uplink-CLI.md
The download links to uplink binaries are almost always out-of-date. This PR replaces them with static links to the latest release in Github.
> Point download links for uplink to latest release

- S3-Gateway.md
The download links to S3 Gateway binaries are almost always out-of-date. This PR replaces them with static links to the latest release in Github.
> Point download links for S3 Gateway to latest release

- code/Endpoint.md
Endpoints which expose a services through gRPC protocol must return
errors with gRPC codes.
> code: endpoint must return gRPC error codes

- code/Service.md
Add to the requirements of service that they must not depend on
transport implementations.
As commented, we should update the example for showing a service which doesn't have any dependency with protocol buffers and make the people raise the point when they find an exception, however right now, I didn't have a good and concise example to replace with.
> code: Services must not depend on transports

- code/Protobuf.md
I think installation by way of scripts/protobuf.go is the best approach
right now, because it will keep everyone on the same versions of the
underlying modules.
Expand discussion of `protolock commit` a little bit now that we're in
all-grown-up no-more-backwards-incompatibilities land.
> update protobuf docs somewhat

- Windows-Installer-Contributor-Guide.md
Update the windows contributor guide with the necessary step of tagging a version for building the windows installer.
> windows contributor guide: add the need for a version tag

- Test-network.md
To create the initial `teststorj` database, use a one line docker command rather than suggesting logging into the postgres shell + running a sql command.
> Test-network.md: add simpler method for creating initial postgres database

- Test-network.md
The latest version of the Postgres docker container requires you to set a password when you run it. This updates the docs to reflect that. It also helpfully includes a snippet to add your `go/bin` to your `$PATH` to make the rest of the setup process quicker.
> test-network: Update instructions for running with postgres

- code/Gerrit.md
We have information about Gerrit scattered around, but I want one
easy-to share public resource to help with onboarding.
> code/Gerrit: Add Gerrit docs

- docs/api-reference/s3-compatible-gateway/multipart-upload/multipart-part-size.md
multipart_threshold actually refers to maximum size of a file when AWS cli switches to using multipart requests (instead of a single API call).
The correct config flag to use is multipart_chunksize
See https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#multipart-threshold
> multipart-part-size.md: Clarify the correct AWS config flag

- app/node/get-started/install-node-software/cli/storage-node/page.md
- app/node/get-started/install-node-software/gui-windows/storage-node/page.md
See https://forum.storj.io/t/disqualified-after-3-years/23645
> added a warning about the danger of using symlinks in the storage location

- app/dcs/code/static-site-hosting/custom-domains/page.md
We are suggesting users to enable strict mode with custom domains and Linksharing TLS. This won't work, because we require that you don't proxy at all if using Linksharing TLS, otherwise certificate creation/renewal challenges will fail.
It sort of works if you first create the certificate on Linksharing, _then_ change Cloudflare to proxy and set the mode to strict, but this is not reliable because it will fail in 3 months when the certificate is attempted to be renewed.
I will add a new dedicated section about using Cloudflare and other proxies with Linksharing TLS in another change.
> Remove steps about using full strict with Cloudflare

- app/node/get-started/install-node-software/cli/docker/page.md
Docker removed direct links from their release notes page, and now it's not possible to find downloads for older version in their documentation
> updated links to 2.1.0.5 versions of Docker Desktop

- app/dcs/api/s3/s3-compatibility/page.md
This updates the page with the latest storj.io/gateway/docs/s3-compatibility.md to make it the ground truth and prepare for removal of storj.io/gateway/docs/s3-compatibility.md. It also adds another context for GetBucketLocation from https://github.com/storj/docs/pull/285, superseding this pull request.
> app/dcs/api/s3/s3-compatibility: update with the latest storj.io/gateway/docs/s3-compatibility.md

- app/dcs/api/uplink-cli/access-command/access-inspect-command/page.md
- app/dcs/api/uplink-cli/access-command/access-register/page.md
- app/dcs/api/uplink-cli/setup-command/page.md
- app/dcs/api/uplink-cli/share-command/page.md
- app/dcs/code/static-site-hosting/custom-domains/page.md
- app/dcs/code/static-site-hosting/page.md
- app/dcs/third-party-tools/docker/page.md
base-url and auth-service already have defaults, so we don't need to use them in the example commands and it will be less confusing to the user.
> Clean up use of base-url and auth-service in command examples

- app/node/payouts/page.md
Older payout rates from July 1st, 2023 were shown. Now they show updated rates starting from December 1st, 2023
> docs/payouts: Payout rates updated to show change from Dec 1st, 2023

- app/node/payouts/zk-sync-opt-in-for-snos/page.md
We adding this option to the `config.yaml` by default, so adding a second one will crash the node
> fixed adding zkSync wallet feature

- app/dcs/code/partner-program-tools/page.md
It allows to set a user-agent for the buckets/prefixes/objects
> fixed the name and format of the legacy config.ini file for Uplink CLI

- app/dcs/migrate/page.md
- app/dcs/pricing/page.md
- app/node/payouts/page.md
- app/page.md
This PR replaces all instances of "$7.00 per TB per month for egress" with "$7.00 per TB for egress". Egress is instantaneous, and not per-month.
* Storage costs are "$x per TB per month", aka "$x per TB-month", because you get charged that for each additional month you store data.
* Egress costs are charged any time you egress the data. If you egress the data once on 2024-01-01, and again on 2024-01-02, you get charged twice, back-to-back.
* Thus, egress cost units are per "amount egressed", and have no concept of time in the units.
* This misunderstanding is not present (i.e., is correct) on the [Storj pricing page](https://www.storj.io/pricing).
> Fix per-month misunderstanding of egress cost

- app/dcs/third-party-tools/iconik/page.md
Iconik is always spelled with a lowercase "i" on their website.
Added section for performance tuning.
> casing and broken link

- app/(docs)/node/get-started/install-node-software/cli/storage-node/page.md
https://forum.storj.io/t/storagenode-docker-update-changes-to-binaries-location-for-persistence-between-restarts/27937
> added warning to apply execution permissions for `bin` subfolder

- app/(docs)/node/get-started/install-node-software/cli/storage-node/page.md
- app/(docs)/node/get-started/prerequisites/page.md
Related to:
* https://github.com/storj/storagenode-docker/pull/25
* https://github.com/storj/storagenode-docker/issues/23
Some restricted systems (e.g. NASes) cannot be adapted to apply `exec` permission to the data location
> removed requirement to have an `exec` permission for the data location

- app/(docs)/learn/concepts/file-repair/page.md
The URL scheme changed, removing dates in URL
eg. (right)
https://storj.io/blog/reputation-matters-when-it-comes-to-storage-nodes/
instead of (wrong)
https://storj.io/blog/2019/01/reputation-matters-when-it-comes-to-storage-nodes/
> Update page.md links to storj.io/blog

- app/(docs)/dcs/buckets/delete-buckets/page.md
removed --force flag to allow to delete the empty bucket with Object Lock enabled, otherwise it throws an error "Access Denied"
> removed --force flag from deleting the empty bucket with Object Lock

- app/(docs)/object-mount/installation/mac/page.md
Called out native macos installer is in beta, and the following instructions are for running the LInux version inside a container.
> Update MacOS Install Instructions

- app/(blog)/blog/page.js
- app/robots.js
- app/sitemap.js
- package-lock.json
- package.json
- src/components/Share.js
- src/components/bio.js
- src/lib/image-tool.js
Bump Next to the last stable version to mitigate CVE-2025-29927.
The new major version required to fix the robots and sitemap files.
The build reported warning about using `img` tags instead of `Image`, where the second is more optimal These warnings have been resolved in this commit.
Closes https://github.com/storj/storj-private/issues/1217
> deps: Bump Next version to mitigate CVE-2025-29927

- src/components/Prose.jsx
Remove blockquote from the text inside a warning box because it makes very hard to read the text in dark mode.
Before
After
> docs: Remove blockquote from warning

- app/(docs)/node/get-started/quic-requirements/linux-configuration-for-udp/page.md
- app/(docs)/node/get-started/quic-requirements/macosfreebsd-configuration-for-udp/page.md
https://forum.storj.io/t/changes-to-the-udp-buffer-size-for-quic-needed/30362/9?u=alexey
I can confirm on my node
```
$ grep "increase receive buffer size" /mnt/x/storagenode2/storagenode.log | tail
2025-07-02T16:15:34Z    INFO    failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.   {"Process": "storagenode"}
2025-07-09T01:40:46Z    INFO    failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.   {"Process": "storagenode"}
```
> increased UDP buffer for QUIC to 7.5MB

- app/(docs)/dcs/pricing/page.md
If you bought a starter package via a partner before August 1, 2025, you will not be charged a minimum usage fee until your starter package expires. The starter package expires one year from purchase or when the starter package credits have been fully used.
> Starter package has an expiration date
