- s3-gateway.md
During my first Tests with the test network I've been confused About this tutorial. So I've Added one sentence stating that there is no Need to run an additional Gateway as the test Network already includes one.
> Fixed a typo and added small info

- Explorer-Release-Setup-Instructions.md
found a small typo in the explorer documentation
> Typo In Explorer Documentation

- Explorer-Release-Setup-Instructions.md
fixed dead link for storj share terms and conditions
> fixed dead link

- S3-Gateway.md
- Uplink-CLI.md
Fix typo for the bash command used for setting up configuration for uplink and gateway
> Fix setup flag

- Uplink-CLI.md
Update uplink-CLI tutorial to use the alpha7 release
> Update of the Uplink cli tutorial

- Explorer-Release-Setup-Instructions.md
based off of the recommendation made in https://ideas.storj.io/ideas/V3-I-11
> updating the instructions for SNOs upgrading

- Test-network.md
Explain how to open the gateway in a web browser, to display a storage node dashboard and how to print the list of environment flags.
> Add explanations about how to play around with the test network

- code/payments/Tally-Vs-Rollup.md
- code/persistentstorage/Satellite-how-to-new-table.md
Add docs that define tally and rollup since those are confusing.
> add tally/rollup doc

- Explorer-Release-Setup-Instructions.md
Added a line for the ARM image for watchtower.
> Add ARM instructions for watchtower

- Explorer-Release-Setup-Instructions.md
Added notes for QNAP NAS. I tested it on QNAP TVS463 and it runs perfect.
> Added notes for QNAP NAS

- code/Style.md
Set the Go language to the snippets which contains Go code.
> style: Mark Go snippets with syntax highlighting

- Test-network.md
- code/persistentstorage/Databases.md
This PR does the following:
- Updates the test docs for how we now create ports for storj-sim
- Add more details to kademlia db docs
- Add steps to run storj-sim with postgres
> update db docs

- code/audits/audit-service.md
Add documentation for audit service functionality/components.
> add audit docs

- code/Testing.md
Add a new section to the document for how to run the different tests
using PostgreSQL database.
> code/Testing: Add section for using PostgreSQL in local

- Explorer-Release-Setup-Instructions.md
The only working version is 0.11.7
You can take a look at https://docs.storj.io/discuss/5d0d3eba44fbd7000e280314
> The version 0.12.6 of identity tool doesn't work

- code/Database.md
Remove an invalid link from the document.
NOTE I haven't been able to find the document, I tried to follow the link from this repo and from the Wiki without success, if you know that the link exist, let me know which is the URL and I will add it back with the right link to.
> code/Database: Remove invalid link

- uplink-cli.md
> Wizard spelled wrong

- Uplink-CLI.md
updated binary's links to v0.15.3
> update to 0.15.3

- code/Style.md
This addition try to capture what we have discussed in slack https://storj.slack.com/archives/CAQV0AE2Z/p1564567179385100
> code/style: Explain when logging is important

- Test-network.md
> update to go 1.13

- Windows-Installer-Contributor-Guide.md
This page should provide helpful instruction for our team and the community on how to contribute improvements to the Windows Installer.
JIRA: https://storjlabs.atlassian.net/browse/V3-2749
> Windows Installer Contributor Guide

- Windows-Installer-Contributor-Guide.md
Add to the requirements to contribute to the Windows Installer the
Microsoft Dot Net version required to be installed in Windows 10.
> Windows-Inst-Contrib: Add DotNet requirement

- code/Peer.md
The satellite peer is now many processes so this PR adds those details.
> update satellite peer docs to include many processes

- code/diagnostics/profiling.md
adds small clarification about profiling heap using pprof
> code/diagnostics/profiling: add a little more info about heap profiling

- code/Style.md
Explain why it's important to sometimes pass some function arguments to
the monkit telemetry calls.
> code/style: Explain extra arguments for telemetry

- Libuplink-Walkthrough.md
> Renamed Tardigrade to Storj DCS

- code/Git.md
> code: Fix typos in Git.md

- Uplink-CLI.md
Storj DCS Uplink CLI documentation link update
> Link to Storj DCS Uplink CLI documentation updated

- app/dcs/api/uplink-cli/access-command/access-restrict/page.md
- app/dcs/api/uplink-cli/share-command/page.md
- app/dcs/buckets/object-lifecycles/page.md
Context: https://github.com/storj/storj/issues/6249
> Docs for Object TTL per access grant / S3 credentials

- app/support/account-management-billing/billing/page.md
Added small change to deposit address description as requested by HU.
> Knowledge_Update_12222023 page.md

- app/node/get-started/prerequisites/page.md
Grammar and sentence structure changes.
> Prerequisites Cleanup

- app/dcs/third-party-tools/veeam/page.md
Removed Immutability (not support with Storj yet)
Updated Storage Optimization language and screenshot
> Update Third Party Tools - Veeam page.md

- app/node/faq/check-logs/page.md
> Minor cleanup

- app/node/faq/check-my-node/page.md
Updated wording to note that email notifications are being sent for downtime, as well as small changes to wording/punctuation.
> Updated Email notifications are now being sent

- app/dcs/third-party-tools/bunny/page.md
> Added Bunny CDN directions

- app/dcs/third-party-tools/mountainduck/page.md
Added Mountain Duck integration guide.  In this process I noticed the Cyberduck guide doesn't clearly describe adding the Storj Profile.  I may go back and fix that too, after sanity checking on Windows.
> Added Mountain Duck integration guide

- app/dcs/pricing/page.md
As requested, removing free tier mentions and also free segments.  Recalculated some math to correct for loss of free segments in examples.
> Removal of Free Tier Part 1.

- app/learn/concepts/limits/page.md
Removed mention of the free tier.  There are some structural sentence changes.
> Remove mention of free tier

- app/dcs/pricing/page.md
Replaced redirect anchor that I removed earlier as per Dan this is necessary.
> Replaced redirect anchor

- app/learn/concepts/limits/page.md
Removed requirement to submit a support request to manually upgrade the account to PRO in case of STORJ tokens
> removed requirement to submit a support request for STORJ tokens

- app/learn/concepts/limits/page.md
* removed mention to file a support request to increase limits if there is only STORJ tokens payment method
* removed evaluation of limit increase requests depending on capacity
> removed mention of filling a support request for STORJ tokens

- app/support/usage-limit-increases/page.md
updating information about free trial.
> Update page.md for free trial info

- app/dcs/third-party-tools/bacula/page.md
- app/dcs/third-party-tools/commvault/page.md
Bacula Community Edition seems impossibly poorly documented, so I skipped it.
> Added Bacula and fixed small Commvault issues

- app/dcs/third-party-tools/globus/page.md
Added optional concurrency modification Globus users can make for better throughput
> Update page.md (Globus Guide)

- app/dcs/third-party-tools/signiant/page.md
> Update page.md (signiant)

- app/node/get-started/prerequisites/page.md
https://forum.storj.io/t/release-preparation-v1-107/26801/11
> updated OS requirements (Windows 8/Windows Server 2012 are out of support)

- app/(docs)/dcs/access/page.md
- app/(docs)/dcs/migrate/backblaze/page.md
- app/(docs)/dcs/migrate/wasabi/page.md
- src/markdoc/partials/create-access-grant.md
- src/markdoc/partials/create-bucket.md
- src/markdoc/partials/s3-credentials.md
Update instructions for Access Keys and remove old screenshots.
> Update docs and images

- app/(docs)/dcs/objects/page.md
- app/(docs)/learn/concepts/access/access-grants/page.md
- app/(docs)/support/account-management-billing/billing/page.md
- app/(docs)/support/account-management-billing/creating-your-account/page.md
- app/(docs)/support/account-management-billing/payment-methods/page.md
- app/(docs)/support/dashboard/page.md
- app/(docs)/support/object-browser/page.md
- app/(docs)/support/projects/page.md
- app/(docs)/support/users/page.md
Update instructions and remove old screenshots.
> Update support pages

- app/(docs)/dcs/third-party-tools/veeam/page.md
Fixed some outdated verbiage on the Veeam docs page
> Update Veeam page.md

- app/(docs)/node/faq/migrate-my-node/page.md
Related to https://github.com/storj/storagenode-docker/issues/23
> added waring to remove binaries from bin after the platform migration

- app/(docs)/dcs/code/static-site-hosting/content-response-headers/page.md
copied from https://github.com/storj/edge/blob/main/docs/linksharing.md#custom-response-metadata
> add content response headers doc

- app/(docs)/node/get-started/prerequisites/page.md
https://forum.storj.io/t/release-preparation-v1-107/26801/11
> updated minimum supported macOS

- app/(docs)/learn/concepts/access/access-grants/api-key/page.md
- app/(docs)/learn/concepts/access/page.md
> fixed link to the Google research about Macaroons

- src/components/Share.js
Replace the old Twitter button (the bird) by the X.
> src/components: Replace button Twitter by X

- package-lock.json
Fix the dependencies suggested by `npm audit fix`.
> deps: Update deps suggested by npm audit fix

- app/(docs)/dcs/buckets/delete-buckets/page.md
> added more alternative methods to delete a bucket

- app/(docs)/object-mount/faq/page.md
+ updated paths for the latest version of Object Mount
> added where configs and license files are located

- app/(docs)/learn/concepts/encryption-key/storj-vs-user-managed-encryption/page.md
- fix reference to "Storj Managed Encryption" that should be "Self-Managed Encryption"
- change "User Managed Encryption" to "Self-Managed Encryption" for consistency with GUI
> improve Storj vs self-managed encryption page

- app/(docs)/object-mount/installation/windows/page.md
Called out native Windows installer is in beta, and the following instructions are for running the LInux version inside WSL.
> Update Windows Install Instructions

- app/(docs)/object-mount/installation/mac/page.md
Adding subheader to clearly explain the page represents using linux containers on macos
> Update macos using linux containers

- app/(docs)/dcs/api/s3/s3-compatibility/page.md
Add bucket tagging
Update listObjects caveats
Closes storj/edge#589
> Update s3 compatibility table

- app/(docs)/node/commercial-node/setup/page.md
- app/(docs)/node/faq/install-storagenode-on-raspberry-pi3-or-higher-version/page.md
- app/(docs)/node/faq/running-node-via-pia/page.md
- app/(docs)/node/get-started/auth-token/page.md
- app/(docs)/node/get-started/identity/page.md
- app/(docs)/node/get-started/install-node-software/cli/page.md
- app/(docs)/node/get-started/install-node-software/gui-windows/page.md
- app/(docs)/node/get-started/install-node-software/page.md
- app/(docs)/node/get-started/port-forwarding/page.md
- app/(docs)/node/get-started/quic-requirements/page.md
- app/(docs)/node/get-started/setup/page.md
- src/markdoc/navigation.mjs
It's not required any more. 
During last few months, we didn't sign our identities at all.
> docs: remove requirement of authorize step for new node install

- package-lock.json
Update the dependencies to mitigate:
- CVE-2025-59343 High severity
- CVE-2025-59343 High severity
> deps: Update deps to mitigate security issues
